### ISSUE TITLE
Wrong code implementation in forest/binary_trees/single_threaded_binary_trees.py

### ISSUE THREAD

**Issue by justyre** [shunsvineyard/forest-python#25]
@shunsvineyard 

Use the following input:

tree = RightThreadedBinaryTree()
tree.insert(key=4, data="")
tree.insert(key=1, data="")
tree.insert(key=7, data="")
tree.insert(key=3, data="")
tree.insert(key=5, data="")
tree.insert(key=2, data="")
tree.insert(key=6, data="")
print(tree)

This will raise an error:

Traceback (most recent call last):
  File "d:\BDSync\Coding\jus\forest-python-by-shun\forest\binary_trees\single_threaded_binary_trees.py", line 275, in <module>
    print(tree)
  File "d:\BDSync\Coding\jus\forest-python-by-shun\forest\binary_trees\single_threaded_binary_trees.py", line 86, in __repr__
    f"tree_height={str(self.get_height(self.root))}"
  File "d:\BDSync\Coding\jus\forest-python-by-shun\forest\binary_trees\single_threaded_binary_trees.py", line 218, in get_height
    RightThreadedBinaryTree.get_height(node.right),
  File "d:\BDSync\Coding\jus\forest-python-by-shun\forest\binary_trees\single_threaded_binary_trees.py", line 218, in get_height
    RightThreadedBinaryTree.get_height(node.right),
  File "d:\BDSync\Coding\jus\forest-python-by-shun\forest\binary_trees\single_threaded_binary_trees.py", line 215, in get_height
    if node.left and node.is_thread is False:
AttributeError: 'NoneType' object has no attribute 'left'

The problem seems to lie in the get_height() method.

**Comment by shunsvineyard** [comment]
The bug has been fixed and merged. https://github.com/shunsvineyard/forest-python/pull/27
